version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ADMIN: ${MYSQL_ADMIN}
    volumes:
      - wordpress_db_data:/var/lib/mysql
    networks:
      - wp_network
    secrets:
      - db_root_password
      - db_password
      - db_user_password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_ADMIN}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - wordpress_site_data:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mariadb
    secrets:
      - db_password
      - db_user_password

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_site_data:/var/www/html:ro
      - ./requirements/nginx/conf:/etc/nginx/conf.d:ro
    networks:
      - wp_network
    depends_on:
      - wordpress

  # Bonus services
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - wp_network

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_site_data:/home/${FTP_USER}
    networks:
      - wp_network
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS_FILE: /run/secrets/ftp_password
    secrets:
      - ftp_password

  static:
    build: ./requirements/bonus/static
    container_name: static
    restart: always
    networks:
      - wp_network
    volumes:
      - ./requirements/bonus/static/site:/usr/share/nginx/html

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    networks:
      - wp_network
    depends_on:
      - mariadb

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    networks:
      - wp_network
    environment:
      PORTAINER_TRUSTED_ORIGINS: "https://igarcia2.42.fr"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

# Vol√∫menes para persistencia
volumes:
  wordpress_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/igarcia2/data/mariadb
  wordpress_site_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/igarcia2/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/igarcia2/data/portainer

# Red dedicada
networks:
  wp_network:

# Secrets
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt

